// mundo2nv4/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from '@angular/core';
import { OnInit } from '@angular/core'; 
import { Router } from '@angular/router'; 
import { Livro } from 'src/app/livro'; 
import { Editora } from '../editora'; 
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})

export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro();
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir(): void {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
} 

<main class="container mt-5">
    <h1 class="mb-4">Adicionar Livro</h1>
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título:</label>
        <input type="text" class="form-control" id="titulo" [(ngModel)]="livro.titulo" name="titulo" required>
      </div>
      <div class="form-group">
        <label for="resumo">Resumo:</label>
        <textarea class="form-control" id="resumo" [(ngModel)]="livro.resumo" name="resumo"></textarea>
      </div>
      <div class="form-group">
        <label for="editora">Editora:</label>
        <select class="form-control" id="editora" [(ngModel)]="livro.codEditora" name="codEditora" required>
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
      <div class="form-group">
        <label for="autores">Autores:</label>
        <textarea class="form-control" id="autores" [(ngModel)]="autoresForm" name="autoresForm"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Adicionar</button>
    </form>
  </main> 
  
  <!-- livro-dados works! -->

// mundo2nv3-livros-react/src/LivroDados.js
import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ControleLivros } from './controle/ControleLivros';
import { ControleEditora } from './controle/Controle.Editora';

const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora();

function LivroDados() {
  const opcoes = controleEditora.getEditoras().map(editora => ({value: editora.codEditora, text: editora.nome}));

  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [autores, setAutores] = useState("");
  const [codEditora, setCodEditora] = useState(opcoes[0].value);

  const navigate = useNavigate();

  function tratarCombo(e) {
    setCodEditora(Number(e.target.value));
  }

  function incluir(e) {
    e.preventDefault();
    const livro = {
      codigo: 0,
      titulo: titulo,
      resumo: resumo,
      autores: autores.split('\n'),
      codEditora: codEditora
    };
    controleLivro.incluir(livro);
    navigate('/');
  }

  return (
    <main className='container'>
      <h1 className='mt-3'>Dados do Livro</h1>
      <form onSubmit={incluir}>
      <div className='mb-3'>
        <label className='form-label' >Título:</label>
        <input type="text" className='form-control' value={titulo} onChange={(e) => setTitulo(e.target.value)} />
        </div>
        <div className='mb-3'>
        <label className='form-label'>Resumo: </label>
        <textarea value={resumo} className=' form-control' onChange={(e) => setResumo(e.target.value)} />
        </div>
        <div className='mb-3'>
        <label className='form-label'>Editora: </label>
        <select className='form-control' value={codEditora} onChange={tratarCombo}>
            {opcoes.map((opcao, index) => <option  key={index} value={opcao.value}>{opcao.text}</option>)}
          </select>
        </div>
        <div className='mb-3'>
        <label className='form-label '>Autores: </label>
        <textarea value={autores} className=' form-control' onChange={(e) => setAutores(e.target.value)} ></textarea>
        <button type="submit" class="btn btn-primary mt-3">Salvar Dados</button>
       </div>
      </form>
    </main>
  );
}

export default LivroDados;
