// mundo2nv4/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from '@angular/core';
import { OnInit } from '@angular/core'; 
import { Router } from '@angular/router'; 
import { Livro } from 'src/app/livro'; 
import { Editora } from '../editora'; 
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css']
})

export class LivroDadosComponent implements OnInit {
  public livro: Livro = new Livro();
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir(): void {
    this.livro.autores = this.autoresForm.split('\n');
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }
} 

<main class="container mt-5">
    <h1 class="mb-4">Adicionar Livro</h1>
    <form (submit)="incluir()" ngNativeValidate>
      <div class="form-group">
        <label for="titulo">Título:</label>
        <input type="text" class="form-control" id="titulo" [(ngModel)]="livro.titulo" name="titulo" required>
      </div>
      <div class="form-group">
        <label for="resumo">Resumo:</label>
        <textarea class="form-control" id="resumo" [(ngModel)]="livro.resumo" name="resumo"></textarea>
      </div>
      <div class="form-group">
        <label for="editora">Editora:</label>
        <select class="form-control" id="editora" [(ngModel)]="livro.codEditora" name="codEditora" required>
          <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
        </select>
      </div>
      <div class="form-group">
        <label for="autores">Autores:</label>
        <textarea class="form-control" id="autores" [(ngModel)]="autoresForm" name="autoresForm"></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Adicionar</button>
    </form>
  </main> 
  
  <!-- livro-dados works! -->

// mundo2nv5-livro-servidor/clientes/livros-react/src/LivroDados.js
import { useState } from "react";
import ControleLivro from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";
import { useNavigate } from "react-router-dom";


const controleLivros = new ControleLivro();
const controleEditora = new ControleEditora();


const LivroDados = props => {
  const opcoes = controleEditora.getEditoras();
  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [autores, setAutores] = useState("");
  const [codEditora, setCodEditora] = useState(opcoes[0]);
  const navigate = useNavigate();

  const tratarCombo = (event) => {
    setCodEditora(Number(event.target.value));
  };

  const incluir = (event) => {
    event.preventDefault();
    const livro = {
      codigo: 0,
      codEditora: codEditora,
      titulo: titulo,
      resumo: resumo,
      autores: autores.split("\n")
    };
    controleLivros.incluir(livro);
    navigate("/");
  };

  return (
    <main class="container">
      <h2>Dados do Livro</h2>
      <form onSubmit={incluir}>
        <div className="form-group" >
          <label htmlFor="titulo">Título</label>
          <input id="titulo" className="form-control" type="text" value={titulo} onChange={(e) => setTitulo(e.target.value)} />
        </div>
        <div>
          <label htmlFor="resumo">Resumo</label>
          <textarea id="resumo" className="form-control" value={resumo} onChange={(e) => setResumo(e.target.value)} />
        </div>
        <div>
          <label htmlFor="editora">Editora</label>
          <select id="editora" className="form-control" value={codEditora} onChange={tratarCombo}>
            {opcoes.map((item) => (
              <option key={item.codEditora} value={item.codEditora}>
                {item.nome}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label htmlFor="autores">Autores</label>
          <textarea id="autores" className="form-control" value={autores} onChange={(e) => setAutores(e.target.value)} />
        </div>
        <button className="btn btn-primary" type="submit">Salvar Livro</button>
      </form>
    </main>
  )
}

export default LivroDados;
